# Usar una imagen base de Python
FROM python:3.12-slim

# directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios al contenedor
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el directorio del proyecto al contenedor
COPY . .

# Exponer el puerto (FastAPI o Flask, preferecnial)
# EXPOSE 8000  # Descomenta si usas un servidor web

# Comando predeterminado para ejecutar el script principal (ajustar según tu caso)
CMD ["python", "scripts/detect.py"]
